on: [push]

name: build

jobs:
  build-rust:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: '1.81.0'

      - name: Build and test Rust backend project
        run: |
          cd backend
          cargo check --verbose
          cargo test --verbose
